/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/k2qBe17T3EQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Component() {
  return (
    <div className="grid grid-cols-[300px_1fr] max-w-4xl w-full rounded-lg overflow-hidden border">
      <div className="bg-muted/20 p-3 border-r">
        <div className="flex items-center justify-between space-x-4">
          <div className="font-medium text-sm">Messenger</div>
          <Button variant="ghost" size="icon" className="rounded-full w-8 h-8">
            <PenIcon className="h-4 w-4" />
            <span className="sr-only">New message</span>
          </Button>
        </div>
        <div className="py-4">
          <form>
            <Input placeholder="Search" className="h-8" />
          </form>
        </div>
        <div className="grid gap-2">
          <Link href="#" className="flex items-center gap-4 p-2 rounded-lg hover:bg-muted/50 bg-muted" prefetch={false}>
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>OM</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Sofia Davis</p>
              <p className="text-xs text-muted-foreground">hey what&apos;s going on? &middot; 2h</p>
            </div>
          </Link>
          <Link href="#" className="flex items-center gap-4 p-2 rounded-lg hover:bg-muted/50" prefetch={false}>
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Alex's Image" />
              <AvatarFallback>AJ</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Alex Johnson</p>
              <p className="text-xs text-muted-foreground">Just finished a great book! 📚 &middot; 45m</p>
            </div>
          </Link>
          <Link href="#" className="flex items-center gap-4 p-2 rounded-lg hover:bg-muted/50" prefetch={false}>
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Maria's Image" />
              <AvatarFallback>MG</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Maria Gonzalez</p>
              <p className="text-xs text-muted-foreground">Excited for the weekend! &middot; 1h</p>
            </div>
          </Link>
          <Link href="#" className="flex items-center gap-4 p-2 rounded-lg hover:bg-muted/50" prefetch={false}>
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Kevin's Image" />
              <AvatarFallback>KB</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Kevin Brown</p>
              <p className="text-xs text-muted-foreground">Who&apos;s up for a movie night? &middot; 3h</p>
            </div>
          </Link>
          <Link href="#" className="flex items-center gap-4 p-2 rounded-lg hover:bg-muted/50" prefetch={false}>
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Lily's Image" />
              <AvatarFallback>LW</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Lily White</p>
              <p className="text-xs text-muted-foreground">Morning coffee is the best! ☕ &middot; 30m</p>
            </div>
          </Link>
        </div>
      </div>
      <div>
        <div className="p-3 flex border-b items-center">
          <div className="flex items-center gap-2">
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>OM</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Sofia Davis</p>
              <p className="text-xs text-muted-foreground">Active 2h ago</p>
            </div>
          </div>
        </div>
        <div className="grid gap-4 p-3">
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm ml-auto bg-primary text-primary-foreground">
            Hey hope you&apos;re doing well! We should catch up sometime soon. 🙏
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm bg-muted">
            Sure! I&apos;m free this weekend if you want to grab a coffee.
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-xl overflow-hidden text-sm ml-auto">
            <img
              src="/placeholder.svg"
              alt="photo"
              width={200}
              height={150}
              className="object-cover"
              style={{ aspectRatio: "200/150", objectFit: "cover" }}
            />
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm ml-auto bg-primary text-primary-foreground">
            Sounds good! Let&apos;s meet at the Starbucks on 5th Ave.
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm bg-muted">
            I&apos;ll message you on Saturday.
          </div>
        </div>
        <div className="border-t">
          <form className="flex w-full items-center space-x-2 p-3">
            <Input id="message" placeholder="Type your message..." className="flex-1" autoComplete="off" />
            <Button type="submit" size="icon">
              <span className="sr-only">Send</span>
              <SendIcon className="h-4 w-4" />
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}

function PenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
